### ISSUE TITLE
Why are only hawtio-core and hawtio-core-navigation JavaScript plugins?

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-core#11]
It's just a question out of curiosity. Were there any reasons these plugins needed to be started as a JavaScript plugin (not TypeScript) at the beginning?  Probably related to #9...

**Comment by gashcrumb** [comment]
Hey!  Yeah, mostly because I hadn't figured out at the time a good way to share typescript definition files between components.  To be honest, I'd been meaning to switch 'em over to typescript all along, but too much other stuff to do.  As long as the exported symbols fit these existing interfaces it's totally do-able to migrate the code to typescript, which would make it easier to maintain 'em:

https://github.com/hawtio/hawtio-core-dts/blob/master/hawtio-core.d.ts

https://github.com/hawtio/hawtio-core-dts/blob/master/hawtio-core-navigation.d.ts

**Comment by tadayosi** [comment]
OK, thanks for the clarification @gashcrumb !
