### ISSUE TITLE
Configuring protractor against an app using HawtioPluginLoader is unclear

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-core#14]
See hawtio/hawtio#2398.

**Comment by benjaminapetersen** [comment]
I'm ok with moving this issue here, other than I disagree (strongly) about leaving this for Hawtio v2 unless the upgrade path is clear & painless & available immediately (for an Angular 1.x app).  If not, then it is alarming that it would be considered acceptable to leave 1.x in a state where e2e testing is not prioritized!  Meddling with Angular's core bootstrapping & ignoring testability is a pretty nasty side effect to including this component.

We have a need for this improvement in the Openshift Web Console on our current version of Hawtio.  See [this issue & PR](https://github.com/openshift/origin-web-console/pull/2083).  While we have addressed some issues getting our e2e running on both Linux & MacOS, Hawtio is creating problems due to the manual boostrapping & it is difficult to know how to comply with Protractor's [system setup guide](http://www.protractortest.org/#/system-setup).

Thanks!

**Comment by tadayosi** [comment]
@benjaminapetersen AFAIK OpenShift Web Console relies only on hawtio v2. I've never heard that the console uses hawtio v1. Is it wrong???

**Comment by benjaminapetersen** [comment]
Aaah, thought you might have been speaking in terms of something like an Angular2 version only.    My bad then, we good!

**Comment by benjaminapetersen** [comment]
Seems like the most reasonable solution is to replace the [bootstrap element](https://github.com/hawtio/hawtio-core/blob/master/src/hawtio-core.ts#L252) and/or allow the user to configure it.  Interested in fixing this, however, I'm not sure what other projects are using the loader and hesitant to make a change w/o being able to test what may break.

**Comment by akieling** [comment]
I'm adding a comment from @gashcrumb , which was responsible for hawtio a while ago:

> Yeah, it's definitely worth giving it a try.  I've looked at getting e2e tests going with hawtio a few times and have never quite gotten protractor working with the manual bootstrapping, but that manual bootstrapping is what allows hawtio to do it's plugin loading.
> 
> Quick stack overflow check shows we're not the only ones but maybe this is worth trying -> https://stackoverflow.com/questions/25596706/using-protractor-test-with-bootstrapped-angularjs
>

**Comment by benjaminapetersen** [comment]
Great, any info helping move this in the right direction is a +1.

**Comment by akieling** [comment]
@benjaminapetersen if you can, have a look at the code and see if there is a way to fix the issue without major changes

**Comment by benjaminapetersen** [comment]
@akieling willing to help where I can, but def would like to see someone more intimately familiar with Hawtio also taking a stab @ it!

**Comment by benjaminapetersen** [comment]
Throwing another suggestion out there, perhaps there is a way to provide configuration so that Hawtio falls back to a regular loading scheme while under test.  For example, register a regular angular module & drop everything in there.

Trying to offer some out of box suggestions.  Not sure if its really possible to alter behavior while under test.

**Comment by alexkieling** [comment]
Is this still an issue?
