### ISSUE TITLE
Help plugin - Sub tabs show up even under FAQ and Change Log

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-core#17]
I believe those sub tabs (`Connect`, `JMX`, `Logs`, ...) should be only visible under **User Guide**.

![screen shot 2018-01-12 at 14 13 23](https://user-images.githubusercontent.com/156692/34860718-cfbf1668-f7a2-11e7-9df3-b7d66c305d71.png)

**Comment by tadayosi** [comment]
@akieling Not sure if it's directly connected to this issue. Should we file an another issue for switching to angular routes instead?  I totally agree on your suggestion, though.

**Comment by tadayosi** [comment]
Done #18

**Comment by tadayosi** [comment]
@akieling Fixed?  It would be really helpful if you could add this issue number in the fix commit comment. Thanks.

**Comment by akieling** [comment]
@tadayosi Unfortunately, I've already pushed the commit and would need to force another push with the amended commit message. That could cause issues for other developers, right?
The commit that fixes this issue is:
https://github.com/hawtio/hawtio-core/commit/c48d26ce6987ba7f66f1fecb3446fbd3b30a198b

**Comment by tadayosi** [comment]
@akieling Yeah, that's ok to leave it as-is for this one. Thanks.
